# Generated by Django 3.2.8 on 2021-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('state', models.TextField()),
                ('IDNum', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
