# Generated by Django 3.2.8 on 2021-11-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0002_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitem',
            name='answer',
        ),
    ]
