# Generated by Django 3.2.8 on 2021-11-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0003_remove_pollitem_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitem',
            name='pollList',
        ),
        migrations.DeleteModel(
            name='PollList',
        ),
    ]
